### ISSUE TITLE
The lidar_centerpoint package can not download model automatically due to LIB_TORCH NOT FOUND

### ISSUE THREAD

**Issue by xczhanjun** [autowarefoundation/autoware#106]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

lidar_centerpoint model can not download model automatically due to LIB_TORCH NOT FOUND

### Expected behavior

lidar_centerpoint model can download model automatically

### Actual behavior

lidar_centerpoint model can not download model automatically due to LIB_TORCH NOT FOUND

### Steps to reproduce

ros2 launch tier4_perception_launch perception.launch.xml mode:=lidar

output is :
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /autoware/install/lidar_centerpoint/share/lidar_centerpoint/config/default.param.yaml

### Versions

ROS2

**Comment by kenji-miyake** [comment]
Thank you for reporting this, but please wait for https://github.com/autowarefoundation/autoware.universe/pull/480 to be merged.

**Comment by yukke42** [comment]
@xczhanjun https://github.com/autowarefoundation/autoware.universe/pull/480 is merged, but the detected objects of lidar_centerpoint isn't published because of other problem.
Please try [the link](https://github.com/autowarefoundation/autoware.universe/issues/643#issuecomment-1090090877), to use lidar_centerpoint.
