### ISSUE TITLE
[Docker] lidar_centerpoint executable could not be built without LibTorch

### ISSUE THREAD

**Issue by IshitaTakeshi** [autowarefoundation/autoware#24]
lidar_centerpoint cannot be built on Docker since the current Dockerfile doesn't install libtorch. 

lidar_centerpoint [explicitly requires libtorch installation](https://github.com/autowarefoundation/autoware.universe/blob/tier4/proposal/perception/lidar_centerpoint/CMakeLists.txt#L71) to build the executable so we need to add the lines to download and install libtorch on the Dockerfile or ansible.

**Comment by kenji-miyake** [comment]
It's intended. Since the `libtorch` role only supports `x86` and uses TIER IV's Google Drive, I decided not to include it in this repository.
https://github.com/tier4/AutowareArchitectureProposal.proj/blob/474da436880f93bd59d87107bd9d83254b0cd9b3/ansible/roles/libtorch/tasks/main.yml#L5

Please install it from [TIER IV's proposal repository](https://github.com/tier4/AutowareArchitectureProposal.proj).

Regarding the future plan, TIER IV will try to use `TensorRT` and remove `libtorch` dependency from `lidar_centerpoint`.
