### ISSUE TITLE
The location of autoware_auto_msgs

### ISSUE THREAD

**Issue by wep21** [autowarefoundation/autoware#84]
Currently `autoware_auto_msgs` repository for `universe` and `core` is located in `tier4` group.
I think the repository should be in `autowarefoundation` group.

**Comment by wep21** [comment]
@xmfcx @mitsudome-r @kenji-miyake Thoughts?

**Comment by xmfcx** [comment]
@wep21 Let's keep them there for now. We will discuss the final messages structure as we finalize the design. And recreate the repository in `autowarefoundation` group with the updated messages.

And we will switch to using them instead in the universe repository.

**Comment by xmfcx** [comment]
The messages won't be `autoware_auto_msgs` anymore, I think we should name them `autoware_msgs` and update https://index.ros.org/p/autoware_msgs/github-autoware-ai-messages/ for our use case, what do you think?

Since we will only update the `galactic` and later, old messages could stay the way they are.

**Comment by kenji-miyake** [comment]
I think so, too.
https://github.com/autowarefoundation/autoware.universe/issues/142
https://github.com/autowarefoundation/autoware/blob/47f8d0e15f9c327c1c45c9b726f9970e5edf2430/autoware.repos#L5

But I'll leave this issue to Fatih-san and Mitsudome-san.

**Comment by kenji-miyake** [comment]
Move to https://github.com/autowarefoundation/autoware_msgs/issues/2.
